// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALSNNexKweBECGPv_JawXeFh4ZhRVPP5E',
    appId: '1:34696971954:web:973bd21f656b6d6ef16bab',
    messagingSenderId: '34696971954',
    projectId: 'ecom-learn-app',
    authDomain: 'ecom-learn-app.firebaseapp.com',
    storageBucket: 'ecom-learn-app.firebasestorage.app',
    measurementId: 'G-YZB18QHLSK',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn9aE3ypyHFfOUHzaVgmDJqEGgK6Xwycc',
    appId: '1:34696971954:ios:918688e78322d61bf16bab',
    messagingSenderId: '34696971954',
    projectId: 'ecom-learn-app',
    storageBucket: 'ecom-learn-app.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBn9aE3ypyHFfOUHzaVgmDJqEGgK6Xwycc',
    appId: '1:34696971954:ios:918688e78322d61bf16bab',
    messagingSenderId: '34696971954',
    projectId: 'ecom-learn-app',
    storageBucket: 'ecom-learn-app.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALSNNexKweBECGPv_JawXeFh4ZhRVPP5E',
    appId: '1:34696971954:web:b22c914298e1a49bf16bab',
    messagingSenderId: '34696971954',
    projectId: 'ecom-learn-app',
    authDomain: 'ecom-learn-app.firebaseapp.com',
    storageBucket: 'ecom-learn-app.firebasestorage.app',
    measurementId: 'G-SPR9R262R6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq8H3RDpC_EBYQr8UvfIdKDAhtCMm6he8',
    appId: '1:34696971954:android:94337fbd806bbd90f16bab',
    messagingSenderId: '34696971954',
    projectId: 'ecom-learn-app',
    storageBucket: 'ecom-learn-app.firebasestorage.app',
  );

}